sdk install java 17.0.11-jbr
mvn clean package -DskipTest

docker build -t juan321/springboot-oracle-be:latest .
docker login -u juan321
(token)
docker push juan321/springboot-oracle-be:latest

docker run --name springboot-oracle-be -e DATABASE_URL=jdbc:oracle:thin:@developer_medium?TNS_ADMIN=Wallet_developer -e DATABASE_USERNAME=DEVELOPER -e DATABASE_PASSWORD=12345 -e PORT=8090 -e SERVER_URL=https://ubiquitous-enigma-xx6vxjv9w6xh997v-8090.app.github.dev -p 8090:8090 juan321/springboot-oracle-be:latest

docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -aq)


---------------------------------------------
#FROM openjdk:17-alpine
#FROM eclipse-temurin:17-alpine
FROM eclipse-temurin:17-jre-alpine
RUN addgroup -S spring && adduser -S spring -G spring
WORKDIR /app
COPY --chown=spring:spring target/*.jar app.jar
COPY --chown=spring:spring Wallet_developer /app/Wallet_developer
USER spring:spring
ENTRYPOINT ["java", "-jar", "app.jar"]

---------------------------------------------
# Stage 1: Build
# FROM maven:3.9.0-eclipse-temurin-17 AS build
FROM maven:3.9.0-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jre-alpine
RUN addgroup -S spring && adduser -S spring -G spring
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
COPY Wallet_developer /app/Wallet_developer
USER spring:spring
ENTRYPOINT ["java", "-jar", "app.jar"]
