CREATE TABLE customer (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    dni CHAR(8) NOT NULL UNIQUE,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    state CHAR(1) NOT NULL
);


CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(5,2) NOT NULL,
    stock NUMBER NOT NULL,
    state CHAR(1) NOT NULL
);


CREATE TABLE sale (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    sale_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total NUMBER(5,2) NOT NULL,
    state CHAR(1) NOT NULL,
    CONSTRAINT FK_SALE_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id)
);


CREATE TABLE sale_detail (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sale_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    subtotal NUMBER(5,2) NOT NULL,
    state CHAR(1) NOT NULL,
    CONSTRAINT FK_SALE_DETAIL_SALE FOREIGN KEY (sale_id) REFERENCES SALE(ID),
    CONSTRAINT FK_SALE_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);


--SELECT *  FROM customer;
--SELECT *  FROM product;
--SELECT *  FROM sale;
--SELECT *  FROM sale_detail;


/*
http://localhost:8085/swagger-ui/index.html
{
  "customerId": 1,
  "products": [
    {
      "productId": 1,
      "quantity": 3
    },
    {
      "productId": 2,
      "quantity": 4
    }
  ]
}
*/